FROM php:7.2-apache

# configuration d'Apache
COPY apache.conf /etc/apache2/conf-enabled/custom.conf

# Install Xdebug
RUN pecl install -f xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini;

RUN a2enmod rewrite

RUN docker-php-ext-install pdo pdo_mysql