version: '3'
services:
    php70:
        container_name: php70
        image: php:7.0-fpm
        build:
            context: php-fpm/7.0/
            dockerfile: Dockerfile.prod
        restart: always
        environment:
            XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9003 remote_enable=1
        ports:
            - "9070:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm
        depends_on:
            - smtp
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "2"

    php72:
        container_name: php72
        image: php:7.2-fpm
        build:
            context: php-fpm/7.2/
            dockerfile: Dockerfile.prod
        restart: always
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9072:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm
        depends_on:
            - smtp
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "2"

    php74:
        container_name: php74
        image: php:7.4-fpm
        build:
            context: php-fpm/7.4/
            dockerfile: Dockerfile.prod
        restart: always
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9074:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm
        depends_on:
            - smtp
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "2"

    php80:
        container_name: php80
        image: php:8.0-fpm
        build:
            context: php-fpm/8.0/
            dockerfile: Dockerfile.prod
        restart: always
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9080:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm
        depends_on:
            - smtp
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "2"

    smtp:
        image: namshi/smtp
        container_name: smtp
        restart: always
        # ports:
        #     - "25:25"
        # environment:
            # MUST start with : e.g RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16
            # if acting as a relay this or RELAY_DOMAINS must be filled out or incoming mail will be rejected
            # - RELAY_NETWORKS= :192.168.0.0/24
            # what domains should be accepted to forward to lower distance MX server.
            # - RELAY_DOMAINS= <domain1>:<domain2>:<domain3>
            # To act as a Gmail relay
            # - GMAIL_USER=
            # - GMAIL_PASSWORD=
            # For use with Amazon SES relay
            # - SES_USER=
            # - SES_PASSWORD=
            # - SES_REGION=
            # if provided will enable TLS support
            # - KEY_PATH=
            # - CERTIFICATE_PATH=
            # the outgoing mail hostname
            # - MAILNAME=
            # set this to any value to disable ipv6
            # - DISABLE_IPV6=
            # Generic SMTP Relay
            # - SMARTHOST_ADDRESS=172.17.0.1
            # - SMARTHOST_ADDRESS=wsus.takoma.fr
            # - SMARTHOST_PORT=25
            # - SMARTHOST_USER=
            # - SMARTHOST_PASSWORD=
            # - SMARTHOST_ALIASES=
        networks:
            - lamp_fpm
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "2"

networks:
    lamp_fpm:
