version: '3'
services:
    httpd24:
        container_name: apache_24
        build: httpd/2.4
        image: apache:2.4
        ports:
            - 80:80
        networks:
            - lamp_fpm
        volumes:
            - "./httpd/2.4/conf.d:/usr/local/apache2/conf/conf.d"
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        depends_on: 
            - php70
            - php72
            - php74
            - php80

    mysql57:
        container_name: mysql_57
        image: mysql:5.7
        # sql-mode: tweak if needed (SELECT @@sql_mode)
        # max_allowed_packet: increase on demand, ex: 256M
        command: --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
        volumes:
            - "${DB_VOLUME}:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: laka28
        ports:
            - "13306:3306"
        networks:
            lamp_fpm:

    php70:
        container_name: php70
        image: php:7.0-fpm
        build:
            context: php-fpm/7.0/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'on'
                DOCKER_PHP_PRODUCTION: 'off'
        environment:
            XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9003 remote_enable=1
        ports:
            - "9070:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        depends_on:
            - mysql57
        networks:
            - lamp_fpm

    php72:
        container_name: php72
        image: php:7.2-fpm
        build:
            context: php-fpm/7.2/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'on'
                DOCKER_PHP_PRODUCTION: 'off'
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9072:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        depends_on:
            - mysql57
        networks:
            - lamp_fpm

    php74:
        container_name: php74
        image: php:7.4-fpm
        build:
            context: php-fpm/7.4/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'on'
                DOCKER_PHP_PRODUCTION: 'off'
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9074:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        depends_on:
            - mysql57
        networks:
            - lamp_fpm

    php80:
        container_name: php80
        image: php:8.0-fpm
        build:
            context: php-fpm/8.0/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'on'
                DOCKER_PHP_PRODUCTION: 'off'
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9080:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        depends_on:
            - mysql57
        networks:
            - lamp_fpm

networks:
    lamp_fpm:
