version: '3'
services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 88:88
        networks:
            - lamp_fpm
        volumes:
            - "./nginx/conf.d:/etc/nginx/conf.d:ro"
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        depends_on:
            - php70
            - php72
            - php74
            - php80
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    httpd24:
        container_name: apache_24
        build: httpd/2.4
        image: apache:2.4
        ports:
            - 80:80
        networks:
            - lamp_fpm
        volumes:
            - "./httpd/2.4/conf.d:/usr/local/apache2/conf/conf.d"
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        depends_on:
            - php70
            - php72
            - php74
            - php80
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    php70:
        container_name: php70
        image: php:7.0-fpm
        build:
            context: php-fpm/7.0/
        environment:
            XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9003 remote_enable=1
        user: 33:33
        ports:
            - "9070:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
            - root-ssh:/root/.ssh
        depends_on:
            - mysql57
            - mysql80
            # - mariadb10
        networks:
            - lamp_fpm
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    php72:
        container_name: php72
        image: php:7.2-fpm
        build:
            context: php-fpm/7.2/
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        user: 33:33
        ports:
            - "9072:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
            - root-ssh:/root/.ssh
        depends_on:
            - mysql57
            - mysql80
            # - mariadb10
        networks:
            - lamp_fpm
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    php74:
        container_name: php74
        image: php:7.4-fpm
        build:
            context: php-fpm/7.4/
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        user: 33:33
        ports:
            - "9074:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
            - root-ssh:/root/.ssh
        depends_on:
            - mysql57
            - mysql80
            # - mariadb10
        networks:
            - lamp_fpm
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    php80:
        container_name: php80
        image: php:8.0-fpm
        build:
            context: php-fpm/8.0/
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        user: 33:33
        ports:
            - "9080:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
            - root-ssh:/root/.ssh
        depends_on:
            - mysql57
            - mysql80
            # - mariadb10
        networks:
            - lamp_fpm
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    mysql57:
        container_name: mysql_57
        image: mysql:5.7
        # sql-mode: tweak if needed (SELECT @@sql_mode)
        # max_allowed_packet: increase on demand, ex: 256M
        command: --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
        volumes:
            - "${DB_VOLUME}/mysql_57:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: laka28
        ports:
            - "3357:3306"
        networks:
            lamp_fpm:
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    mysql80:
        container_name: mysql_80
        image: mysql:8.0
        # sql-mode: tweak if needed (SELECT @@sql_mode)
        # max_allowed_packet: increase on demand, ex: 256M
        command: --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
        volumes:
            - "${DB_VOLUME}/mysql_80:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: laka28
        ports:
            - "3380:3306"
        networks:
            lamp_fpm:
        logging:
            driver: "json-file"
            options:
                max-size: "200k"

    # mariadb10:
    #     container_name: mariadb_10
    #     image: mariadb:10
    #     # sql-mode: tweak if needed (SELECT @@sql_mode)
    #     # max_allowed_packet: increase on demand, ex: 256M
    #     command: --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
    #     volumes:
    #         - "${DB_VOLUME}/mariadb_10:/var/lib/mysql"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: laka28
    #     ports:
    #         - "3410:3306"
    #     networks:
    #         lamp_fpm:
    #     logging:
    #         driver: "json-file"
    #         options:
    #             max-size: "200k"

networks:
    lamp_fpm:

volumes:
    root-ssh:
