version: '3'
services:
    # httpd24:
    #     container_name: apache_24
    #     build: httpd/2.4
    #     image: apache:2.4
    #     ports:
    #         - 80:80
    #     networks:
    #         - lamp_fpm
    #     volumes:
    #         - "./httpd/2.4/conf.d:/usr/local/apache2/conf/conf.d"
    #         - "${WEB_VOLUME_DATA}:/var/www/data"
    #         - "${WEB_VOLUME_DEV}:/var/www/dev"
    #     depends_on: 
    #         - php70
    #         # - php72
    #         # - php74

    mysql57:
        container_name: mysql_57
        image: mysql:5.7
        # sql-mode: tweak if needed (SELECT @@sql_mode)
        # max_allowed_packet: increase on demand, ex: 256M
        command: --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
        volumes:
            #- "d:/database/docker/mysql_57:/var/lib/mysql"
            - "${DB_VOLUME}:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: laka28
        ports:
            - "13306:3306"
        networks:
            lamp_legacy:
                aliases:
                    - db
            # lamp_fpm:

    # php70:
    #     container_name: php70
    #     image: php:7.0-fpm-alpine
    #     build:
    #         context: php-fpm/7.0/
    #         args:
    #             DOCKER_PHP_ENABLE_COMPOSER: 'on'
    #             DOCKER_PHP_ENABLE_MYSQL: 'on'
    #             DOCKER_PHP_ENABLE_XDEBUG: 'on'
    #             DOCKER_USER_UID: 1000
    #             DOCKER_USER_GID: 1000
    #     ports:
    #         - "127.0.0.1:9070:9000"
    #         - 9900
    #     volumes:
    #         - "${WEB_VOLUME_DATA}:/var/www/data"
    #         - "${WEB_VOLUME_DEV}:/var/www/dev"
    #     depends_on:
    #         - mysql57
    #     networks:
    #         - lamp_fpm

    # php72:
    #     container_name: php72
    #     # build: php/7.0_apache
    #     image: php:7.2-fpm-alpine
    #     # environment:
    #     #     XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9000 remote_enable=1
    #     expose:
    #         - 9000
    #     ports:
    #         - "127.0.0.1:9072:9000"
    #     volumes:
    #         - "${WEB_VOLUME_DATA}:/var/www/data"
    #         - "${WEB_VOLUME_DEV}:/var/www/dev"
    #     depends_on:
    #         - mysql57
    #     networks:
    #         - lamp_fpm

    # php74:
    #     container_name: php74
    #     # build: php/7.0_apache
    #     image: php:7.4-fpm-alpine
    #     # environment:
    #     #     XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9000 remote_enable=1
    #     expose:
    #         - 9000
    #     ports:
    #         - "127.0.0.1:9074:9000"
    #     volumes:
    #         - "${WEB_VOLUME_DATA}:/var/www/data"
    #         - "${WEB_VOLUME_DEV}:/var/www/dev"
    #     depends_on:
    #         - mysql57
    #     networks:
    #         - lamp_fpm

    web70:
        container_name: php70_apache
        build: php/7.0_apache
        image: php_apache:7.0
        environment:
            XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9000 remote_enable=1
        ports:
            - "7080:80"
        volumes:
            - "./apache/conf:/etc/apache2/custom"
            - "./apache/log:/var/log/apache2"
            - "${WEB_VOLUME_DATA}:/home/docker/data"
            - "${WEB_VOLUME_DEV}:/home/docker/dev"
        depends_on:
            - mysql57
        networks:
            - lamp_legacy

    web72:
        container_name: php72_apache
        build: ./php/7.2_apache
        image: php_apache:7.2
        environment:
            XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9000 remote_enable=1
        ports:
            - "7280:80"
        volumes:
            - "./apache/conf:/etc/apache2/custom"
            - "./apache/log:/var/log/apache2"
            - "${WEB_VOLUME_DATA}:/home/docker/data"
            - "${WEB_VOLUME_DEV}:/home/docker/dev"
        depends_on:
            - mysql57
        networks:
            - lamp_legacy

    web74:
        container_name: php74_apache
        build: ./php/7.4_apache
        image: php_apache:7.4
        environment:
            XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9000 remote_enable=1
        ports:
            - "7480:80"
        volumes:
            - "./apache/conf:/etc/apache2/custom"
            - "./apache/log:/var/log/apache2"
            - "${WEB_VOLUME_DATA}:/home/docker/data"
            - "${WEB_VOLUME_DEV}:/home/docker/dev"
        depends_on:
            - mysql57
        networks:
            - lamp_legacy

networks:
    lamp_legacy:
    # lamp_fpm:
