version: '3'
services:
    php70:
        container_name: php70
        image: php:7.0-fpm
        build:
            context: php-fpm/7.0/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'off'
                DOCKER_PHP_PRODUCTION: 'on'
        restart: always
        environment:
            XDEBUG_CONFIG: remote_host=${WEB_REMOTE_HOST} remote_port=9003 remote_enable=1
        ports:
            - "9070:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm

    php72:
        container_name: php72
        image: php:7.2-fpm
        build:
            context: php-fpm/7.2/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'off'
                DOCKER_PHP_PRODUCTION: 'on'
        restart: always
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9072:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm

    php74:
        container_name: php74
        image: php:7.4-fpm
        build:
            context: php-fpm/7.4/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'off'
                DOCKER_PHP_PRODUCTION: 'on'
        restart: always
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9074:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm

    php80:
        container_name: php80
        image: php:8.0-fpm
        build:
            context: php-fpm/8.0/
            args:
                DOCKER_PHP_ENABLE_XDEBUG: 'off'
                DOCKER_PHP_PRODUCTION: 'on'
        restart: always
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_SESSION: VSCODE
            XDEBUG_CONFIG: client_host=${WEB_REMOTE_HOST} start_with_request=trigger
        ports:
            - "9080:9000"
        volumes:
            - "${WEB_VOLUME_DATA}:/var/www/data"
            - "${WEB_VOLUME_DEV}:/var/www/dev"
        networks:
            - lamp_fpm
networks:
    lamp_fpm:
